# variables used throughout the project
count = 0
david_defence = False
marekec_dodge = False
mojmir_double_damage = False
mojmir_attack = False
mojmir_done = False
mata_poison = False
mata_here = False
kvitek_ultimate = False
zimik_reduce_energy = False
end = False
mata_poison_target = ''
winner = ''
available_characters = ['david', 'matyas', 'mojmir', 'honza', 'zimik', 'kvitek', 'mark', 'milan', 'nikolas', 'pavel', 'petr', 'tom']
first_player_collection = []
second_player_collection = []
all_unplayable = []
transfer = {}
all_playable = []
inverted_transfer = {v: k for k, v in transfer.items()}
first_player_playable = []
second_player_playable = []