all_available = ['Anus', 'Big Chungus', 'Kvítek', 'Marekec', 'Máta', 'Milanus', 'Mojmi-chan', 'PopeC0rn', 'Tolbus', 'Zálabář', 'Žeromán', 'Žimík']
first_collection, second_collection, first_playable, second_playable = [], [], [], []
all_characters, all_playable = [], []
transfer, inv_transfer = {}, {}
already_played = {}
choosing_finish = False
chungus_defence = False
mata_here = False
mata_poison = False
mojmir_attack = ''
mojmi_chan_double_damage = False
mojmi_chan_done = False
mata_poison_target = ''
marekec_dodge = False
kvitek_ultimate = False
zimik_reduce_energy = False
end, winner = False, ''
count = 1