all_available = ['david', 'honza', 'kvitek', 'mark', 'matyas', 'milan', 'mojmir', 'nikolas', 'pavel', 'petr', 'tom', 'zimik']
first_collection = []
second_collection = []
all_characters = []
all_playable = []
transfer = {}
inv_transfer = {}
choosing_finish = False
mata_here = False