all_available = ['David', 'Honza', 'Kvítek', 'Mark', 'Matyáš', 'Milan', 'Mojmír', 'Nikolas', 'Pavel', 'Petr', 'Tom', 'Žimík']
first_collection, second_collection, first_playable, second_playable = [], [], [], []
all_characters, all_playable = [], []
transfer, inv_transfer = {}, {}
already_played = {}
choosing_finish = False
david_defence = False
mata_here = False
mata_poison = False
mojmir_attack = ''
mojmir_double_damage = False
mojmir_done = False
mata_poison_target = ''
marekec_dodge = False
kvitek_ultimate = False
zimik_reduce_energy = False
end, winner = False, ''
count = 1